class LPocket{
	constructor(){
		this.array=[];
		this.pocket=document.createElement("DIV");
		this.pocket.className="pocket";
		document.body.appendChild(this.pocket);
	}
	showed(Wind){
		for(var i=0;i<this.array.length;i++){
			if(this.array[i].Lwindow==Wind){
				this.array[i].className="pocketElem act";
			}else{
				this.array[i].Lwindow.Chide();
			}
		}
	}
	hided(Wind){
		for(var i=0;i<this.array.length;i++){
			if(this.array[i].Lwindow==Wind){
				this.array[i].className="pocketElem";
			}
		}
	}
	add(Wind, src){
		var div=document.createElement("DIV");
		div.className="pocketElem";
		div.Lwindow=Wind;
		div.onclick=function(e){e.currentTarget.Lwindow.CreSee();};
		var img=document.createElement("IMG");
		img.src=src;
		img.alt="О";
		div.appendChild(img);
		this.pocket.appendChild(div);
		this.array.push(div);
		this.pocket.style.display="inline-block";
	}
	fetchArray(){
		var aaa=[];
		for(var i=0;i<this.array.length;i++){
			if(this.array[i]!=null){
				aaa.push(this.array[i]);
			}
		}
		this.array=aaa;
	}
	remove(Wind){
		for(var i=0;i<this.array.length;i++){
			if(this.array[i].Lwindow==Wind){
				this.array[i].remove();
				this.array[i]=null;
				this.fetchArray();
			}
		}
		if(this.array.length==0){
			this.pocket.style.display="none";
		}
	}
}	
class LWindow{
	constructor(info){
		this.see=false;
		this.deleted=false;
		this.initialize();
		if(info==undefined){
			info=new Object();
			info.exit=true;
		}
		if(info.html!=undefined){
			this.setHTML(info.html);
		}
		if(info.caption!=undefined){
			this.setCaption(info.caption);
		}
		if(info.exit==true){
			this.setExit(true);
		}
		if(info.hide==true){
			this.setHide(true);
		}
		if(info.pocket!=undefined){
			this.pocket=info.pocket;
			info.pocket.add(this, info.src)
		}
	}
	Cfocus(){
		if(this.deleted){
			return;
		}
		this.initCheck();
		this.root.focus();
	}
	CreSee(){
		if(this.see){
			this.Chide();
		}else{
			this.Cshow();
		}
	}
	Cshow(){
		this.see=true;
		if(this.deleted){
			return;
		}
		if(this.pocket!=undefined){
			this.pocket.showed(this);
		}
		this.initCheck();
		this.Cfocus();
		this.root.style.display="inline-block";
		this.closer.style.display="inline-block";
	}
	Chide(){
		if(this.pocket!=undefined){
			this.pocket.hided(this);
		}
		this.see=false;
		if(this.deleted){
			return;
		}
		this.initCheck();
		this.root.style.display="none";
		this.closer.style.display="none";
	}
	Cexit(){
		if(this.deleted){
			return;
		}
		if(this.pocket!=undefined){
			this.pocket.remove(this);
		}
		this.exited=true;
		this.deinitialize();
	}
	Cdelete(){
		if(this.deleted){
			return;
		}
		this.Cexit();
		this.deleted=true;
	}
	deinitialize(){
		if(this.deleted){
			return;
		}
		if(document.body.windows!=undefined){
			var windowst=[];
			for(var i=0; i<document.body.windows.length; i++){
				if(document.body.windows[i]!=this){
					windowst.push(document.body.windows[i]);
				}
			}
			document.body.windows=windowst;
		}
		this.initialized=false;
		this.root.remove();
		this.closer.remove();
	}
	initCheck(){
		if(this.deleted){
			return;
		}
		if(!this.initialized){
			this.initialize();
		}
	}
	initialize(){
		if(this.deleted){
			return;
		}
		if(document.body.windows!=undefined){
			var was=true;
			for(var i=0; i<document.body.windows.length; i++){
				if(document.body.windows[i]==this){
					was=false;
					break;
				}
			}
			if(was){
				document.body.windows.push(this);
			}
		}else{
			document.body.windows=[this];
		}
		this.initialized=true;
		this.closer=document.createElement("DIV");
		this.closer.className="closer";
		this.closer.style.display="none";
		this.root=document.createElement("DIV");
		this.root.className="window";
		this.root.style.display="none";
		this.root.commander=this;
		this.panel=document.createElement("DIV");
		this.panel.className="panel";
		this.caption=document.createElement("DIV");
		this.caption.className="caption";
		this.container=document.createElement("DIV");
		this.container.className="container";
		this.root.appendChild(this.panel);
		this.root.appendChild(this.caption);
		this.root.appendChild(this.container);
		document.body.appendChild(this.closer);
		document.body.appendChild(this.root);
		if(this.exited){
			this.reload();
		}
	}
	setExit(texit){
		if(this.deleted){
			return;
		}
		this.initCheck();
		if(texit!=this.exit){
			if(texit){
				this.exit=true;
				this.setButtons();
			}else{
				this.exit=false;
				this.panel.getElementsByClassName('exit').remove();
			}
		}
	}
	setHide(thide){
		if(this.deleted){
			return;
		}
		this.initCheck();
		if(thide!=this.hide){
			if(thide){
				this.hide=true;
				this.setButtons();
			}else{
				this.hide=false;
				this.panel.getElementsByClassName('hide').remove();
			}
		}
	}
	setCaption(capt){
		if(this.deleted){
			return;
		}
		this.caption.innerHTML=capt;
		this.captionText=capt;
	}
	setHTML(thtml){
		if(this.deleted){
			return;
		}
		this.initCheck();
		this.html=thtml;
		this.container.innerHTML=thtml;
	}
	setButtons(){
		if(this.deleted){
			return;
		}
		this.initCheck();
		var htmlk="";
		if(this.exit){
			htmlk+='<div class="exit" onclick="this.parentNode.parentNode.commander.Cexit();" title="Alt+C">X</div>';
		}
		if(this.hide){
			htmlk+='<div class="hide" onclick="this.parentNode.parentNode.commander.Chide();" title="Alt+H">_</div>';
		}
		this.panel.innerHTML=htmlk;
	}
	reload(){
		if(this.deleted){
			return;
		}
		this.initCheck();
		this.caption.innerHTML=((this.captionText==undefined)?("Окно"):(this.captionText));
		this.container.innerHTML=((this.html==undefined)?(""):(this.html));
		this.setButtons();
	}
}
window.addEventListener("load", function(){
	document.body.addEventListener("keydown", function(evt){
		if(evt.keyCode==27){
			if(this.windows!=undefined){
				for(var i=0; i<this.windows.length; i++){
					this.windows[i].Chide();
				}
			}
		}
		if((evt.keyCode==67)&&evt.altKey&&(!evt.ctrlKey)){
			if(this.windows!=undefined){
				for(var i=0; i<this.windows.length; i++){
					if(this.windows[i].see){
						this.windows[i].Cexit();
					}
				}
			}
		}
		if((evt.keyCode==72)&&evt.altKey){
			if(this.windows!=undefined){
				for(var i=0; i<this.windows.length; i++){
					if(this.windows[i].see){
						this.windows[i].Chide();
					}
				}
			}
		}
		if((evt.keyCode==67)&&evt.altKey&&evt.ctrlKey){
			if(this.windows!=undefined){
				for(var i=0; i<this.windows.length; i++){
					window.setTimeout(function(){document.body.windows[document.body.windows.length-1].Cexit();}, 60*(i+1));
				}
			}
		}
	}, false);
}, false);